processing:
  buffer_size_in_cubes: 10000
  buffer_size_in_cubes_downsampling: 10000
  num_downsampling_cores: 10
  num_io_threads: 10
  cube_edge_len: 128
  skip_already_cubed_layers: True
  skip_already_downsampled_cubes: True
dataset:
  scale:
    - 12
    - 12
    - 25